[package]
authors = ["camsi6"]
edition = "2018"
readme = "README.md"
name = "cross-compilation"
version = "0.1.0"

[dependencies]
geranium_rt = { path = "../geranium_rt" }
#cortex-m = "0.6.0"
#cortex-m-rt = "0.6.10"
#panic-halt = "0.2.0"